#!/bin/sh
# Author:     MyHR, Andy <andy.myhr@metlife.com>
# Contact:    awmyhr <awmyhr@gmail.com>
# Project:    Shell Functions
# Proj Home:  https://github.com/awmyhr/shell-functions
# Copyright:  2019 awmyhr
# License:    Apache-2.0
# Revised:    2019-06-28 # This revision is for the test-suite portion
# Created:    2019-06-28
##--==
#!/bin/sh
#-- NOTE: Default to POSIX shell/mode. Be mindful of your reasons before
#--       switching to Bash, and consider using Python instead...
#==============================================================================
#:"""
#: .. program:: {{ script_name|default("TODO: CHANGEME", true) }}
#:    :synopsis: {{ script_synopsis|default("TODO: CHANGEME", true) }}
#:
#:    :copyright: {{ software_copyright|default("TODO: CHANGEME", true) }}
#:    :license: {{ software_license|default("TODO: CHANGEME", true) }}
#:
#: .. codeauthor:: {{ full_name|default("TODO: CHANGEME", true) }} <{{ email|default("TODO: CHANGEME", true) }}>
#:
#: .. note:
#:     For guidance, please refer to:
#:
#:         - 'POSIX.1-2008 Base Specification, Issue 7 <http://pubs.opengroup.org/onlinepubs/9699919799/nframe.html>'_
#:         - 'GNU Coding Standard <http://www.gnu.org/prep/standards/>'_
#:
#: .. note:
#:     ShellCheck should be used, accepted issues should be marked w/disable comment
#:
#: .. warning:
#:     Option parsing is currently less-than-ideal
#:
#: {{ script_description|default("TODO: CHANGEME- description for documentation", true) }}
#:"""
#==============================================================================
#: .. section:: Preamble (script-specific vars -- override this)
#: .. revision:: 2019-06-28
#------------------------------------------------------------------------------
#-- Variables which are meta for the script should be dunders (__varname__)
#-- TODO: UPDATE meta vars
__version__='{{ version|default("TODO: CHANGEME", true) }}' #: current version
__revised__='20181207-144952' #: date of most recent revision
__contact__='{{ contact_name|default("TODO: CHANGEME", true) }} <{{ contact_email|default("TODO: CHANGEME", true) }}>' #: primary contact for support/?'s
__synopsis__='{{ script_synopsis|default("TODO: CHANGEME", true) }}'
__description__="
{{ script_description|default('TODO: CHANGEME - description for --help', true) }}
"
#------------------------------------------------------------------------------
#-- TODO: If you want to hard-set some variables, do it here. For example:
# BACKUP_DSF:="+%Y%m%d-%H%M%S"
# DEFAULT_TIMESTAMP="+%Y%m%d-%H%M%S"
# LOGGER_DSF="+%Y%m%d-%H%M%S"
# LOGGER_FILE="${HOME}/var/log/{{ script_name|default("script_logger", true) }}.$(date +%Y%m%d-%H%M%S).log"
# LOGGER_LVL:="info"
#------------------------------------------------------------------------------
#-- Flags
__require_root__='false'    #: Does script require root
__container_safe__='false'  #: Are we safe to run inside a Docker container?
__gnu_version__='false'     #: If true print GNU version string (which includes copyright/license)
__script_debug__='false'    #: This can be set to 'true' via --debug paramater
#==============================================================================
#-- The following few variables should be relatively static over life of script
__author__='{{ full_name|default("TODO: CHANGEME", true) }} <{{ email|default("TODO: CHANGEME", true) }}>' #: coder(s) of script
__created__='{{ date|default("TODO: CHANGEME", true) }}'               #: date script originlly created
__copyright__='{{ software_copyright|default("TODO: CHANGEME", true) }}' #: Copyright short name
__license__='{{ software_license|default("TODO: CHANGEME", true) }}'
__cononical_name__='{{ script_name|default("TODO: CHANGEME", true) }}' #: static name, *NOT* os.path.basename(sys.argv[0])
__project_name__='{{ project_name|default("TODO: CHANGEME", true) }}'  #: name of overall project, if needed
__project_home__='{{ project_home|default("TODO: CHANGEME", true) }}'  #: where to find source/documentation
__template_version__='2.13.0'  #: version of template file used
##==---
#==============================================================================
if ! (return 0 2>/dev/null) ; then
    if [ "${RUN_UNIT_TEST}" = 'true' ] ; then
        printf '__author__="%s"\n' "${__author__}"
        printf '__cononical_name__="%s"\n' "${__cononical_name__}"
        printf '__contact__="%s"\n' "${__contact__}"
        printf '__container_safe__="%s"\n' "${__container_safe__}"
        printf '__copyright__="%s"\n' "${__copyright__}"
        printf '__created__="%s"\n' "${__created__}"
        printf '__description__="%s"\n' "${__description__}"
        printf '__gnu_version__="%s"\n' "${__gnu_version__}"
        printf '__license__="%s"\n' "${__license__}"
        printf '__project_home__="%s"\n' "${__project_home__}"
        printf '__project_name__="%s"\n' "${__project_name__}"
        printf '__require_root__="%s"\n' "${__require_root__}"
        printf '__revised__="%s"\n' "${__revised__}"
        printf '__script_debug__="%s"\n' "${__script_debug__}"
        printf '__synopsis__="%s"\n' "${__synopsis__}"
        printf '__template_version__="%s"\n' "${__template_version__}"
        printf '__version__="%s"\n' "${__version__}"
    fi
fi
