#!/bin/sh
# Author:     MyHR, Andy <andy.myhr@metlife.com>
# Contact:    awmyhr <awmyhr@gmail.com>
# Project:    Shell Functions
# Proj Home:  https://github.com/awmyhr/shell-functions
# Copyright:  2019 awmyhr
# License:    Apache-2.0
# Revised:    2019-07-05 # This revision is for the test-suite portion
# Created:    2019-06-28
##--==
#==============================================================================
_debug_info() {
    #:"""
    #: .. function:: _debug_info()
    #:
    #: .. project:: Shell Functions <https://github.com/awmyhr/shell-functions>
    #:
    #: .. revision:: 2019-07-05
    #:
    #: Provides meta info for debug-level output
    #:
    #: .. note::
    #:     We set script_path here to avoid calling cd/dirname/pwd when not really needed
    #:"""
##==---
    #-- Expected globals ------------------------------------------------------
    __author__="${__author__:=unknown <unknown>}"
    __basename__="${__basename__:=${0}}"
    __cononical_name__="${__cononical_name__:=unknown}"
    __contact__="${__contact__:=unknown <unknown>}"
    __created__="${__created__:=yyyy-mm-dd}"
    __original_args__="${__original_args__:=${*}}"
    __project_home__="${__project_home__:=unknown}"
    __project_name__="${__project_name__:=unknown}"
    __revised__="${__revised__:=yyyymmdd-hhmmss}"
    __template_version__="${__template_version__:=z.y.x}"
    __version__="${__version__:=x.y.z}"
    #--------------------------------------------------------------------------
##--==
    # shellcheck disable=SC1007
    script_path="$(CDPATH= cd -- "$(dirname -- "${0}")" && pwd )"

    logln debug "Cononical: ${__cononical_name__}"
    logln debug "Abs Path:  ${script_path}/${__basename__}"
    logln debug "Args List: ${__original_args__}"
    logln debug "Version:   ${__version__}"
    logln debug "md5sum:    $(md5sum "${__basename__}" 2>&1)"
    logln debug "Created:   ${__created__}"
    logln debug "Revised:   ${__revised__}"
    logln debug "Coder(s):  ${__author__}"
    logln debug "Contact:   ${__contact__}"
    logln debug "Project:   ${__project_name__}"
    logln debug "Project Home: ${__project_home__}"
    logln debug "Template Version: ${__template_version__}"
    logln debug "System:    $(uname -orv 2>&1)"
    logln debug "Hostname:  $(hostname 2>&1)"
    logln debug "Logname:   ${USERNAME:=$(logname 2>&1)}"
    logln debug "[re]uid:   $(id -ur 2>&1)/$(id -u 2>&1)"
    logln debug "PID/PPID:  ${$}/${PPID}"
    if [ -x /bin/pstree ] || [ -x /usr/bin/pstree ] ; then
        if pstree -psu ${$} 1>/dev/null 2>&1 ; then
            logln debug "pstree psu: $(pstree -psu ${$})"
        else
            logln debug "pstree pu: $(pstree -pu ${$})"
        fi
    fi
    logln debug '-----------------'
    logln debug '----- start -----'
    logln debug '-----------------'

    return
}
##==---
#==============================================================================
if ! (return 0 2>/dev/null) ; then
    if [ "${RUN_UNIT_TEST}" = 'true' ] ; then
        md5sum() {
            printf 'TestTestTest'
        }
    fi
    if ! declare -f logln >/dev/null 2>&1 ; then
        logln() {
            printf '%s %s\n' "${1}" "${2}"
        }
    fi

    _debug_info "${@}"
fi
