#!/bin/sh
# Author:     awmyhr <awmyhr@gmail.com>
# Contact:    awmyhr <awmyhr@gmail.com>
# Project:    Shell Functions
# Proj Home:  https://github.com/awmyhr/shell-functions
# Copyright:  2019 awmyhr
# License:    Apache-2.0
# Revised:    2019-07-05 # This revision is for the test-suite portion
# Created:    2019-06-28
##--==
#==============================================================================
exit_clean() {
    #:"""
    #: .. function:: exit_clean()
    #:
    #: .. project:: Shell Functions <https://github.com/awmyhr/shell-functions>
    #:
    #: .. revision:: 2019-07-05
    #:
    #: Clean up everything and exit gracefully
    #: .. warning::
    #:     This function exits the script
    #:"""
##==---
    #-- Expected globals ------------------------------------------------------
    __logln_dsf__="${__logln_dsf__:="+%Y%m%d"}"
    __logln_file__="${__logln_file__:=unknown}"
    __logln_file_set__=${__logln_file_set__:='false'}
    __script_debug__=${__script_debug__:='false'}
    #--------------------------------------------------------------------------
##--==
    [ "${__script_debug__}" = true ] && {
        set +o xtrace
        logln debug '-----------------'
        logln debug '------ end ------'
        logln debug '-----------------'
        __script_debug__=false
    }

    trap - INT TERM HUP
    if [ "${__logln_file_set__}" = "true" ]; then
        printf '%s [EXIT]: Script finished.\n' "$(get_timestamp "${__logln_dsf__}")" 1>&3
        printf 'Log file created: %s\n' "${__logln_file__}"
        exec 3>&-
    fi
    exit 0

    return
}
##==---
#==============================================================================
if ! (return 0 2>/dev/null) ; then
    if [ "${RUN_UNIT_TEST}" = 'true' ] || ! declare -f logln >/dev/null 2>&1 ; then
        logln() {
            printf '%s %s\n' "${1}" "${2}"
        }
        get_timestamp() {
            printf '%s' "${1}"
        }
        exec 3>&1 || exit 1
    fi
    if [ "${1}" = debug ] ; then
        __script_debug__='true'
    fi
    exit_clean "${@}"
fi
