#!/bin/sh
# Author:     MyHR, Andy <andy.myhr@metlife.com>
# Contact:    awmyhr <awmyhr@gmail.com>
# Project:    Shell Functions
# Proj Home:  https://github.com/awmyhr/shell-functions
# Copyright:  2019 awmyhr
# License:    Apache-2.0
# Revised:    2019-06-28 # This revision is for the test-suite portion
# Created:    2019-06-28
##--==
#==============================================================================
is_false() {
    #:"""
    #: .. function:: is_false()
    #:
    #: .. project:: Shell Functions <https://github.com/awmyhr/shell-functions>
    #:
    #: .. revision:: 2019-06-28
    #:
    #: Check if a string is a standard false flag
    #: Ref: https://github.com/fedora-sysv/initscripts)
    #:
    #: :param str boolean:   String to check
    #:"""# {% raw %}
    if [ "${#}" -ne 1 ] ; then # {% endraw %}
        return 64
    fi
    case "${1}" in
        [fF] | [nN] | [nN][oO] | [fF][aA][lL][sS][eE] | 0) return 0 ;;
        *) return 1
    esac
}
##==---
#==============================================================================
if ! (return 0 2>/dev/null) ; then
    is_false "${@}"
fi
