#!/bin/sh
# Author:     MyHR, Andy <andy.myhr@metlife.com>
# Contact:    awmyhr <awmyhr@gmail.com>
# Project:    Shell Functions
# Proj Home:  https://github.com/awmyhr/shell-functions
# Copyright:  2019 awmyhr
# License:    Apache-2.0
# Revised:    2019-07-05 # This revision is for the test-suite portion
# Created:    2019-06-28
##--==
#==============================================================================
mk_tmp() {
    #:"""
    #: .. function:: mk_tmp()
    #:
    #: .. project:: Shell Functions <https://github.com/awmyhr/shell-functions>
    #:
    #: .. revision:: 2019-07-05
    #:
    #: Creates a temporary file (or directory), returning the path. Defaults to file.
    #:
    #: :param str directory:   Pass any substring of 'directory' to create a directory
    #:
    #:"""
##==---
    #-- Expected globals ------------------------------------------------------
    __cononical_name__="${__cononical_name__:=unknown}"
    #--------------------------------------------------------------------------
##--==
    __mk_tmp_dir='' # {% raw %}
    if [ "${#}" -eq 1 ] ; then # {% endraw %}
        case 'directory' in
            *${1}*) __mk_tmp_dir='-d' ;;
            *)      ;;
        esac ;
    fi
    if command -v mktemp >/dev/null 2>&1; then
        mktemp ${__mk_tmp_dir} -t "${__cononical_name__}${__mk_tmp_dir}.XXXXXXXXXX" || return "${?}"
    else
        if [ "${__mk_tmp_dir}" = '' ]; then
            __mk_tmp_path="/tmp/${__cononical_name__}.${$}"
            touch "${__mk_tmp_path}" || return "${?}"
        else
            __mk_tmp_path="/tmp/${__cononical_name__}-d.${$}"
            mkdir "${__mk_tmp_path}" || return "${?}"
        fi
        printf '%s' "${__mk_tmp_path}"
    fi

    return
}
##==---
#==============================================================================
if ! (return 0 2>/dev/null) ; then
    mk_tmp "${@}"
fi
