#!/bin/sh
# Author:     awmyhr <awmyhr@gmail.com>
# Contact:    awmyhr <awmyhr@gmail.com>
# Project:    Shell Functions
# Proj Home:  https://github.com/awmyhr/shell-functions
# Copyright:  2019 awmyhr
# License:    Apache-2.0
# Revised:    2019-07-05 # This revision is for the test-suite portion
# Created:    2019-06-28
##--==
#==============================================================================
set_value_in_file() {
    #:"""
    #: .. function:: set_value_in_file()
    #:
    #: .. project:: Shell Functions <https://github.com/awmyhr/shell-functions>
    #:
    #: .. revision:: 2019-07-25
    #:
    #: Add or change a KEY to a VALUE in a FILE, creating FILE if necessary.
    #:
    #: :param str file:   FILE to create/modify
    #: :param str key:    KEY to create/modify
    #: :param str value:  VALUE to set key to
    #: :param str quote:  set to 'noquote' if VALUE should not be quoted
    #:"""{% raw %}
    if [ "${#}" -ne 3 ] && [ "${#}" -ne 4 ] ; then # {% endraw %}
        return 64
    fi
    __set_value_in_file_file="${1}"
    __set_value_in_file_key="${2}"
    __set_value_in_file_value="${3}"
    if ! [ "${4}" = 'noquote' ] ; then
        __set_value_in_file_value="'${__set_value_in_file_value}'"
    fi
    if sed -h 2>&1 | grep -q '\-E' ; then
        __set_value_in_file_sedopt='-E'
    else
        __set_value_in_file_sedopt='-r'
    fi

    if [ ! -e "${__set_value_in_file_file}" ] ; then
        touch "${__set_value_in_file_file}" || return "${?}"
    fi
    if grep -q "^${__set_value_in_file_key}=" "${__set_value_in_file_file}" ; then
        sed -i ${__set_value_in_file_sedopt} \
            "s|^${__set_value_in_file_key} *=.*|${__set_value_in_file_key}=${__set_value_in_file_value}|" \
            "${__set_value_in_file_file}" || return "${?}"
    else
        printf '%s=%s\n' "${__set_value_in_file_key}" "${__set_value_in_file_value}" \
            >> "${__set_value_in_file_file}" || return "${?}"
    fi

    return
}
##==---
#==============================================================================
if ! (return 0 2>/dev/null) ; then
    set_value_in_file "${@}"
fi
